# Generated by Django 5.0.3 on 2024-06-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0001_initial'),
        ('segmentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentclass',
            name='segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentor.segment'),
        ),
    ]
