# Generated by Django 5.0.3 on 2024-06-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_driver_safety_score'),
        ('manageTrips', '0004_alter_trip_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_path', models.CharField(max_length=500)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.driver')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTrips.trip')),
                ('Segment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentor.segmenttype')),
            ],
        ),
    ]
