# Generated by Django 5.0.3 on 2024-06-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('initial_lat', models.FloatField()),
                ('initial_long', models.FloatField()),
                ('last_lat', models.FloatField()),
                ('last_long', models.FloatField()),
                ('duration', models.IntegerField()),
                ('distance', models.FloatField()),
                ('csvPath', models.CharField(max_length=500)),
                ('videoPath', models.CharField(max_length=500)),
                ('sensorProcessed', models.BooleanField(default=False)),
                ('videoProcessed', models.BooleanField(default=False)),
            ],
        ),
    ]
