# Generated by Django 5.0.3 on 2024-06-04 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_driver_safety_score'),
        ('manageTrips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='endTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='stratTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehicle'),
        ),
        migrations.CreateModel(
            name='TripScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripScore', models.IntegerField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.driver')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageTrips.trip')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehicle')),
            ],
        ),
    ]
