# Generated by Django 5.0.3 on 2024-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTrips', '0003_rename_strattime_trip_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.CharField(max_length=500),
        ),
    ]
