# Generated by Django 5.0.3 on 2024-06-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageTrips', '0004_alter_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscores',
            name='tripScore',
            field=models.FloatField(),
        ),
    ]
