# Generated by Django 5.0.3 on 2024-06-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageTrips', '0005_alter_tripscores_tripscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripscores',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='tripscores',
            name='vehicle_id',
        ),
    ]
