# Generated by Django 5.0.3 on 2024-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_driver_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='safety_score',
            field=models.FloatField(default=100),
        ),
    ]
